import { AuditLogEntry } from "@/types/notifications";

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud-001",
    timestamp: "2025-03-08 10:42:15",
    user: "Dr. Aarti Sharma",
    role: "Welfare Officer",
    action: "Viewed Welfare Case",
    resource: "CASE-2025-042 (P-1024)",
    status: "Authorized",
    ipAddress: "10.14.82.11",
    details: "Accessed timeline and assigned duty rotation intervention",
  },
  {
    id: "aud-002",
    timestamp: "2025-03-08 10:30:02",
    user: "Ct. Piyush Kumar",
    role: "Personnel",
    action: "Completed Voluntary Assessment",
    resource: "Assessment Engine (Self-Report)",
    status: "Authorized",
    ipAddress: "10.22.104.55",
    details: "Submitted 7-step voluntary wellness metrics with consent",
  },
  {
    id: "aud-003",
    timestamp: "2025-03-08 09:15:40",
    user: "Col. Rajeshwar Singh",
    role: "Commander",
    action: "Viewed Force Welfare Aggregate",
    resource: "Sector HQ Aggregate Analytics",
    status: "Authorized",
    ipAddress: "10.14.80.05",
    details: "Queried unit comparison metrics; individual PII masked",
  },
  {
    id: "aud-004",
    timestamp: "2025-03-08 08:50:22",
    user: "System AI Engine",
    role: "Automated Service",
    action: "Evaluated Risk Indicators",
    resource: "Unit Alpha & Bravo Roster",
    status: "Authorized",
    ipAddress: "127.0.0.1",
    details: "Computed multi-factor predictive stress scores across 1,248 records",
  },
  {
    id: "aud-005",
    timestamp: "2025-03-08 07:22:11",
    user: "External Subnet Query",
    role: "Unknown",
    action: "Attempted Direct Personnel Query",
    resource: "/api/v1/personnel/P-1024/wellness-raw",
    status: "Blocked",
    ipAddress: "192.168.1.189",
    details: "Blocked by Zero-Trust Role Access Guard (Missing Officer Token)",
  },
  {
    id: "aud-006",
    timestamp: "2025-03-07 18:40:00",
    user: "Dr. Aarti Sharma",
    role: "Welfare Officer",
    action: "Created Welfare Intervention",
    resource: "INT-101 (Workload Adjustment)",
    status: "Authorized",
    ipAddress: "10.14.82.11",
    details: "Assigned rotational daytime logistics role to reduce fatigue",
  },
  {
    id: "aud-007",
    timestamp: "2025-03-07 16:15:30",
    user: "Sunil Patel",
    role: "Admin",
    action: "Updated Retention & Consent Policy",
    resource: "Privacy Center Settings",
    status: "Authorized",
    ipAddress: "10.10.10.02",
    details: "Automated 90-day purge enabled for voluntary raw wellness logs",
  },
  {
    id: "aud-008",
    timestamp: "2025-03-07 14:02:18",
    user: "Ct. Piyush Kumar",
    role: "Personnel",
    action: "Updated Consent Preferences",
    resource: "Personal Privacy Controls",
    status: "Authorized",
    ipAddress: "10.22.104.55",
    details: "Verified affirmative opt-in for voluntary fatigue analytics",
  },
];
