import { WelfareAlertItem } from "@/types/notifications";

export const MOCK_NOTIFICATIONS: WelfareAlertItem[] = [
  {
    id: "alert-001",
    category: "Welfare",
    title: "Elevated welfare indicators detected",
    description: "Personnel P-1024 (Bravo Coy) flagged with cumulative fatigue and 142 days forward deployment.",
    timestamp: "10 mins ago",
    priority: "High",
    isRead: false,
    personnelId: "P-1024",
    caseId: "CASE-2025-042",
    contributingIndicators: ["Extended deployment (142 days)", "Elevated workload (68 hrs/wk)", "Reduced recovery (5.5 hrs sleep)"],
    recommendedAction: "Human welfare officer confidential review",
  },
  {
    id: "alert-002",
    category: "Welfare",
    title: "Urgent welfare intervention review required",
    description: "Personnel P-1025 (Alpha Coy) continuous night patrols for 21 days with acute sleep deficit.",
    timestamp: "45 mins ago",
    priority: "Urgent",
    isRead: false,
    personnelId: "P-1025",
    caseId: "CASE-2025-039",
    contributingIndicators: ["Continuous 198 days forward duty", "Sleep deficit below 4.8 hrs", "Overdue annual leave"],
    recommendedAction: "Immediate rotational stand-down and leave clearance",
  },
  {
    id: "alert-003",
    category: "Assessment",
    title: "Voluntary wellness assessment completed",
    description: "Personnel P-1024 submitted voluntary 7-step wellness self-reporting.",
    timestamp: "2 hours ago",
    priority: "Medium",
    isRead: true,
    personnelId: "P-1024",
  },
  {
    id: "alert-004",
    category: "Intervention",
    title: "Welfare intervention scheduled",
    description: "Follow-up check-in scheduled for Personnel P-1024 on 10 March 2025.",
    timestamp: "5 hours ago",
    priority: "Low",
    isRead: true,
    caseId: "CASE-2025-042",
  },
  {
    id: "alert-005",
    category: "System",
    title: "Privacy consent re-verified",
    description: "Sector-wide automated audit verified zero PII exposure to unauthorized roles.",
    timestamp: "1 day ago",
    priority: "Low",
    isRead: true,
  },
];
