import { WelfareCase, AIRecommendation } from "@/types/welfare";

export const MOCK_WELFARE_CASES: WelfareCase[] = [
  {
    id: "CASE-2025-042",
    personnelId: "P-1024",
    anonymizedCode: "SEC-B-882",
    riskLevel: "HIGH",
    primaryConcern: "Extended Deployment & Operational Workload Pressure",
    unit: "Bravo Company",
    assignedOfficer: "Dr. Aarti Sharma",
    assignedOfficerId: "user-welfare-01",
    createdAt: "2025-02-24",
    updatedAt: "2025-03-02",
    status: "Under Review",
    notesCount: 3,
    interventionsCount: 2,
    timeline: [
      {
        id: "tl-1",
        timestamp: "2025-02-24 09:15 AM",
        title: "Welfare Alert Generated",
        description: "AI predictive model flagged continuous 140+ day operational deployment and sleep deficits.",
        actor: "System AI Engine",
        actorRole: "Automated Welfare Monitor",
        type: "alert",
      },
      {
        id: "tl-2",
        timestamp: "2025-02-24 11:30 AM",
        title: "Officer Assigned",
        description: "Assigned to Dr. Aarti Sharma for confidential welfare assessment and preliminary screening.",
        actor: "Welfare Directorate Desk",
        actorRole: "Welfare Coordinator",
        type: "assignment",
      },
      {
        id: "tl-3",
        timestamp: "2025-02-26 03:00 PM",
        title: "Initial Welfare Review Completed",
        description: "Confidential tele-discussion conducted. Personnel expressed fatigue and requested upcoming leave assistance.",
        actor: "Dr. Aarti Sharma",
        actorRole: "Welfare Officer",
        type: "review",
      },
      {
        id: "tl-4",
        timestamp: "2025-02-28 10:00 AM",
        title: "Support Offered & Rotation Proposed",
        description: "Initiated recommendation for 10-day duty rotation away from frontline night duties.",
        actor: "Dr. Aarti Sharma",
        actorRole: "Welfare Officer",
        type: "intervention",
      },
      {
        id: "tl-5",
        timestamp: "2025-03-02 04:30 PM",
        title: "Follow-up Scheduled",
        description: "Scheduled 1-on-1 check-in for March 10th to review leave sanctions and physical recovery.",
        actor: "Dr. Aarti Sharma",
        actorRole: "Welfare Officer",
        type: "followup",
      },
    ],
    interventions: [
      {
        id: "int-101",
        caseId: "CASE-2025-042",
        personnelId: "P-1024",
        type: "Workload Adjustment",
        title: "Rotational Duty Reassignment",
        description: "Transfer from active nighttime perimeter sentry to daylight administrative logistics post.",
        status: "Active",
        scheduledDate: "2025-03-01",
        officerName: "Dr. Aarti Sharma",
        notes: "Approved by Bravo Coy Commander; effective for 14 days.",
      },
      {
        id: "int-102",
        caseId: "CASE-2025-042",
        personnelId: "P-1024",
        type: "Counseling",
        title: "Voluntary Stress Decompression Session",
        description: "Confidential session focusing on sleep hygiene and family communication coping strategies.",
        status: "Completed",
        scheduledDate: "2025-02-27",
        completedDate: "2025-02-27",
        officerName: "Dr. Aarti Sharma",
        notes: "Personnel receptive, responsive to sleep rhythm recommendations.",
      },
    ],
    caseNotes: [
      {
        id: "note-1",
        author: "Dr. Aarti Sharma",
        date: "2025-02-24",
        text: "Case opened automatically from high welfare risk alert. Reviewing duty roster records.",
        isConfidential: true,
      },
      {
        id: "note-2",
        author: "Dr. Aarti Sharma",
        date: "2025-02-26",
        text: "Personnel sounded motivated but weary. Family concerns at home in Rajasthan adding emotional load.",
        isConfidential: true,
      },
      {
        id: "note-3",
        author: "Dr. Aarti Sharma",
        date: "2025-03-02",
        text: "Leave application submitted to Battalion HQ. Awaiting sanction for 15 days casual leave.",
        isConfidential: true,
      },
    ],
  },
  {
    id: "CASE-2025-039",
    personnelId: "P-1025",
    anonymizedCode: "SEC-A-419",
    riskLevel: "URGENT REVIEW",
    primaryConcern: "Severe Cumulative Fatigue & Night Patrol Overload",
    unit: "Alpha Company",
    assignedOfficer: "Dr. Aarti Sharma",
    assignedOfficerId: "user-welfare-01",
    createdAt: "2025-02-18",
    updatedAt: "2025-03-04",
    status: "Intervention",
    notesCount: 4,
    interventionsCount: 2,
    timeline: [
      {
        id: "tl-39-1",
        timestamp: "2025-02-18 08:30 AM",
        title: "Urgent Welfare Indicator Triggered",
        description: "198 continuous deployment days without leave; sleep index below 4.5 hrs.",
        actor: "System AI Engine",
        actorRole: "Automated Welfare Monitor",
        type: "alert",
      },
      {
        id: "tl-39-2",
        timestamp: "2025-02-18 10:00 AM",
        title: "Immediate Officer Action",
        description: "Case marked priority 1 by Welfare Directorate.",
        actor: "Dr. Aarti Sharma",
        actorRole: "Welfare Officer",
        type: "assignment",
      },
      {
        id: "tl-39-3",
        timestamp: "2025-02-20 02:00 PM",
        title: "Intervention Initiated",
        description: "Fast-track leave approved; mandatory stand-down from duty initiated.",
        actor: "Dr. Aarti Sharma",
        actorRole: "Welfare Officer",
        type: "intervention",
      },
    ],
    interventions: [
      {
        id: "int-095",
        caseId: "CASE-2025-039",
        personnelId: "P-1025",
        type: "Recovery Support",
        title: "Mandatory Rest Stand-down",
        description: "72 hours continuous operational stand-down with medical observation.",
        status: "Completed",
        scheduledDate: "2025-02-21",
        completedDate: "2025-02-24",
        officerName: "Dr. Aarti Sharma",
      },
      {
        id: "int-096",
        caseId: "CASE-2025-039",
        personnelId: "P-1025",
        type: "Family Support",
        title: "Priority Annual Leave Sanction",
        description: "Sanction 20 days emergency annual leave for family welfare.",
        status: "Active",
        scheduledDate: "2025-03-06",
        officerName: "Dr. Aarti Sharma",
      },
    ],
    caseNotes: [
      {
        id: "note-39-1",
        author: "Dr. Aarti Sharma",
        date: "2025-02-18",
        text: "Urgent case. Personnel has not visited family in 10 months due to successive operational attachments.",
        isConfidential: true,
      },
    ],
  },
  {
    id: "CASE-2025-045",
    personnelId: "P-1088",
    anonymizedCode: "SEC-E-733",
    riskLevel: "HIGH",
    primaryConcern: "Dense Jungle Ops Terrain Isolation",
    unit: "Echo Company",
    assignedOfficer: "Dr. Aarti Sharma",
    assignedOfficerId: "user-welfare-01",
    createdAt: "2025-02-27",
    updatedAt: "2025-03-01",
    status: "Under Review",
    notesCount: 2,
    interventionsCount: 1,
    timeline: [
      {
        id: "tl-45-1",
        timestamp: "2025-02-27 11:15 AM",
        title: "Welfare Alert Flagged",
        description: "High continuous duty hours and limited communications window flagged.",
        actor: "System AI Engine",
        actorRole: "Automated Welfare Monitor",
        type: "alert",
      },
    ],
    interventions: [
      {
        id: "int-110",
        caseId: "CASE-2025-045",
        personnelId: "P-1088",
        type: "Welfare Assistance",
        title: "Dedicated Welfare Calling Facility",
        description: "Provide priority access to satellite calling terminal at company base.",
        status: "Active",
        scheduledDate: "2025-03-02",
        officerName: "Dr. Aarti Sharma",
      },
    ],
    caseNotes: [
      {
        id: "note-45-1",
        author: "Dr. Aarti Sharma",
        date: "2025-02-27",
        text: "Personnel stationed at deep outpost. Coordination with Company Havildar Major in progress.",
        isConfidential: true,
      },
    ],
  },
  {
    id: "CASE-2025-031",
    personnelId: "P-1042",
    anonymizedCode: "SEC-D-512",
    riskLevel: "MODERATE",
    primaryConcern: "High Altitude Acclimatization & Sleep Disruption",
    unit: "Delta Company",
    assignedOfficer: "Capt. Vivek Nair",
    assignedOfficerId: "user-welfare-02",
    createdAt: "2025-02-10",
    updatedAt: "2025-02-22",
    status: "Resolved",
    notesCount: 3,
    interventionsCount: 1,
    timeline: [
      {
        id: "tl-31-1",
        timestamp: "2025-02-10",
        title: "Alert Generated",
        description: "Moderate sleep deficit and high altitude shift strain detected.",
        actor: "System AI Engine",
        actorRole: "Automated Welfare Monitor",
        type: "alert",
      },
      {
        id: "tl-31-2",
        timestamp: "2025-02-22",
        title: "Case Resolved Successfully",
        description: "Personnel acclimatized, sleep patterns stabilized to 7 hours, duty schedule adjusted.",
        actor: "Capt. Vivek Nair",
        actorRole: "Welfare Officer",
        type: "status_change",
      },
    ],
    interventions: [
      {
        id: "int-088",
        caseId: "CASE-2025-031",
        personnelId: "P-1042",
        type: "Medical Referral",
        title: "Altitude Wellness Evaluation",
        description: "Battalion medical inspection and oxygen saturation monitoring.",
        status: "Completed",
        scheduledDate: "2025-02-12",
        completedDate: "2025-02-15",
        officerName: "Capt. Vivek Nair",
      },
    ],
    caseNotes: [],
  },
];

export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: "REC-2025-01",
    title: "Workload Balancing & Shift Rotation",
    category: "Workload Balancing",
    reason: "Unit Alpha shows sustained elevated workload indicators (74 hrs/wk average).",
    targetUnit: "Alpha Company",
    recommendedAction: "Review duty rotation, redistribute perimeter guards, and schedule mandatory recovery downtime.",
    impactLevel: "High",
    status: "Pending",
    createdAt: "2025-03-03",
  },
  {
    id: "REC-2025-02",
    title: "Cumulative Leave Clearance Drive",
    category: "Recovery Scheduling",
    reason: "Bravo Company personnel have utilized only 21% of accumulated leave entitlement.",
    targetUnit: "Bravo Company",
    recommendedAction: "Sanction rotational 10-day leave batches to prevent end-of-quarter operational burnout.",
    impactLevel: "High",
    status: "Under Review",
    createdAt: "2025-03-02",
  },
  {
    id: "REC-2025-03",
    title: "High Altitude Decompression Scheduling",
    category: "Duty Rotation",
    reason: "Delta Company has spent 110 days in high altitude outposts exceeding standard rotation cycle.",
    targetUnit: "Delta Company",
    recommendedAction: "Coordinate with Sector HQ for planned swap with rear reserve company.",
    impactLevel: "Moderate",
    status: "Assigned",
    createdAt: "2025-02-28",
  },
  {
    id: "REC-2025-04",
    title: "Supportive Family Communication Windows",
    category: "Unit Welfare",
    reason: "Outpost Sukma in Echo Company experiencing extended isolation periods.",
    targetUnit: "Echo Company",
    recommendedAction: "Ensure daily 2-hour satellite telephone welfare connectivity windows for all personnel.",
    impactLevel: "Moderate",
    status: "Completed",
    createdAt: "2025-02-25",
  },
];
