import { PersonnelRecord } from "@/types/personnel";

export const MOCK_PERSONNEL: PersonnelRecord[] = [
  {
    id: "P-1024",
    name: "Ct. Piyush Kumar",
    rank: "Constable (GD)",
    unit: "Bravo Company",
    deploymentLocation: "Forward Post Dantewada",
    deploymentDurationDays: 142,
    continuousDutyHours: 14,
    lastLeaveDate: "2024-10-12",
    leaveDaysTakenYTD: 12,
    leaveEntitlementDays: 60,
    workloadScore: 78,
    workloadStatus: "Elevated",
    recoveryTimeHours: 5.5,
    dutyHoursPerWeek: 68,
    assignedOfficerId: "user-welfare-01",
    assignedOfficerName: "Dr. Aarti Sharma",
    anonymizedCode: "SEC-B-882",
  },
  {
    id: "P-1025",
    name: "HC. Ramesh Yadav",
    rank: "Head Constable",
    unit: "Alpha Company",
    deploymentLocation: "Sector HQ Srinagar",
    deploymentDurationDays: 198,
    continuousDutyHours: 16,
    lastLeaveDate: "2024-08-04",
    leaveDaysTakenYTD: 8,
    leaveEntitlementDays: 60,
    workloadScore: 88,
    workloadStatus: "Severe",
    recoveryTimeHours: 4.8,
    dutyHoursPerWeek: 74,
    assignedOfficerId: "user-welfare-01",
    assignedOfficerName: "Dr. Aarti Sharma",
    anonymizedCode: "SEC-A-419",
  },
  {
    id: "P-1033",
    name: "ASI. Gurmeet Singh",
    rank: "Assistant Sub-Inspector",
    unit: "Charlie Company",
    deploymentLocation: "Border Outpost Ranian",
    deploymentDurationDays: 64,
    continuousDutyHours: 9,
    lastLeaveDate: "2025-01-10",
    leaveDaysTakenYTD: 24,
    leaveEntitlementDays: 60,
    workloadScore: 48,
    workloadStatus: "Optimal",
    recoveryTimeHours: 7.5,
    dutyHoursPerWeek: 46,
    anonymizedCode: "SEC-C-104",
  },
  {
    id: "P-1042",
    name: "SI. Manoj Deshmukh",
    rank: "Sub-Inspector",
    unit: "Delta Company",
    deploymentLocation: "High Altitude Leh Base",
    deploymentDurationDays: 110,
    continuousDutyHours: 12,
    lastLeaveDate: "2024-11-20",
    leaveDaysTakenYTD: 18,
    leaveEntitlementDays: 60,
    workloadScore: 66,
    workloadStatus: "Moderate",
    recoveryTimeHours: 6.2,
    dutyHoursPerWeek: 56,
    anonymizedCode: "SEC-D-512",
  },
  {
    id: "P-1088",
    name: "Ct. Arvind Minz",
    rank: "Constable",
    unit: "Echo Company",
    deploymentLocation: "Jungle Warfare Camp Sukma",
    deploymentDurationDays: 165,
    continuousDutyHours: 15,
    lastLeaveDate: "2024-09-18",
    leaveDaysTakenYTD: 10,
    leaveEntitlementDays: 60,
    workloadScore: 84,
    workloadStatus: "Severe",
    recoveryTimeHours: 5.0,
    dutyHoursPerWeek: 71,
    assignedOfficerId: "user-welfare-01",
    assignedOfficerName: "Dr. Aarti Sharma",
    anonymizedCode: "SEC-E-733",
  },
  {
    id: "P-1102",
    name: "Ct. Ananya Rawat",
    rank: "Constable (Comms)",
    unit: "Alpha Company",
    deploymentLocation: "Comm Centre Guwahati",
    deploymentDurationDays: 45,
    continuousDutyHours: 8,
    lastLeaveDate: "2025-02-01",
    leaveDaysTakenYTD: 28,
    leaveEntitlementDays: 60,
    workloadScore: 40,
    workloadStatus: "Optimal",
    recoveryTimeHours: 8.0,
    dutyHoursPerWeek: 42,
    anonymizedCode: "SEC-A-901",
  }
];
