import { PersonnelRecord, AIRecommendation, InterventionRecord, AuditLogEntry } from "../types";

export const MOCK_PERSONNEL_ROSTER: PersonnelRecord[] = [
  {
    id: "P-1024",
    serviceNumber: "CRPF-984214",
    name: "Ct. Vikramaditya Singh",
    rank: "Constable (GD)",
    unit: "74 Bn Bravo Coy",
    force: "CRPF",
    location: "Sukma Sector, Bastar",
    bloodGroup: "B+",
    consecutiveFieldDays: 142,
    workloadHoursWeekly: 68,
    riskScore: 84,
    riskLevel: "High",
    antiMaskingFlag: true,
    lastAssessmentDate: "2026-09-10",
  },
  {
    id: "P-1025",
    serviceNumber: "ARMY-881290",
    name: "Nk. Rajesh Gurung",
    rank: "Naik",
    unit: "3/11 Gorkha Rifles",
    force: "ARMY",
    location: "Siachen Base Camp",
    bloodGroup: "O+",
    consecutiveFieldDays: 98,
    workloadHoursWeekly: 62,
    riskScore: 78,
    riskLevel: "High",
    antiMaskingFlag: true,
    lastAssessmentDate: "2026-09-09",
  },
  {
    id: "P-1026",
    serviceNumber: "BSF-442109",
    name: "HC. Amitav Banerjee",
    rank: "Head Constable",
    unit: "112 Bn Delta Coy",
    force: "BSF",
    location: "Sunderbans Riverine",
    bloodGroup: "A+",
    consecutiveFieldDays: 45,
    workloadHoursWeekly: 52,
    riskScore: 54,
    riskLevel: "Moderate",
    antiMaskingFlag: false,
    lastAssessmentDate: "2026-09-08",
  },
  {
    id: "P-1027",
    serviceNumber: "ITBP-339012",
    name: "Ct. Tenzing Norbu",
    rank: "Constable (Telecom)",
    unit: "21 Bn Charlie Coy",
    force: "ITBP",
    location: "Kaza High Altitude Post",
    bloodGroup: "AB+",
    consecutiveFieldDays: 62,
    workloadHoursWeekly: 48,
    riskScore: 36,
    riskLevel: "Low",
    antiMaskingFlag: false,
    lastAssessmentDate: "2026-09-10",
  },
  {
    id: "P-1028",
    serviceNumber: "CISF-771234",
    name: "ASI. Rameshwar Reddy",
    rank: "Assistant Sub-Inspector",
    unit: "CISF Airport Wing",
    force: "CISF",
    location: "IGIA New Delhi",
    bloodGroup: "O-",
    consecutiveFieldDays: 28,
    workloadHoursWeekly: 44,
    riskScore: 28,
    riskLevel: "Low",
    antiMaskingFlag: false,
    lastAssessmentDate: "2026-09-11",
  },
  {
    id: "P-1029",
    serviceNumber: "CRPF-992145",
    name: "HC. Sandeep Pathak",
    rank: "Head Constable",
    unit: "204 CoBRA Bn",
    force: "CRPF",
    location: "Bijapur Forward Base",
    bloodGroup: "O+",
    consecutiveFieldDays: 130,
    workloadHoursWeekly: 72,
    riskScore: 91,
    riskLevel: "Critical",
    antiMaskingFlag: true,
    lastAssessmentDate: "2026-09-07",
  },
  {
    id: "P-1030",
    serviceNumber: "POLICE-11029",
    name: "SI. Devendra Rathore",
    rank: "Sub-Inspector",
    unit: "Special Task Force",
    force: "POLICE",
    location: "Anti-Extremist Cell",
    bloodGroup: "B-",
    consecutiveFieldDays: 80,
    workloadHoursWeekly: 64,
    riskScore: 66,
    riskLevel: "Moderate",
    antiMaskingFlag: false,
    lastAssessmentDate: "2026-09-09",
  },
];

export const MOCK_INTERVENTIONS: InterventionRecord[] = [
  {
    id: "INT-881",
    personnelId: "P-1024",
    personnelName: "Ct. Vikramaditya Singh",
    personnelRank: "Constable (GD)",
    type: "Mandatory R&R Leave",
    title: "10-Day Recuperation Rotation",
    description: "Personnel accumulated 142 consecutive combat deployment days. Recommend urgent detachment to rear transit camp for medical decompression.",
    initiatedDate: "2026-09-08",
    scheduledDate: "2026-09-12",
    status: "Active",
    priority: "Urgent",
    officerInCharge: "Dr. Ananya Roy (SMO)",
  },
  {
    id: "INT-882",
    personnelId: "P-1029",
    personnelName: "HC. Sandeep Pathak",
    personnelRank: "Head Constable",
    type: "Clinical Counseling",
    title: "Sleep Disruption & Trauma Review",
    description: "Anti-masking divergence confirmed severe autonomic arousal despite stoic self-report. Individual tele-consultation scheduled.",
    initiatedDate: "2026-09-09",
    scheduledDate: "2026-09-11",
    status: "Active",
    priority: "High",
    officerInCharge: "Dr. Ananya Roy (SMO)",
  },
  {
    id: "INT-883",
    personnelId: "P-1025",
    personnelName: "Nk. Rajesh Gurung",
    personnelRank: "Naik",
    type: "Workload Adjustment",
    title: "Night Sentry Sentry Relief",
    description: "Shifted from night observation post rotation to day quarter-guard to restore biological sleep rhythm.",
    initiatedDate: "2026-09-05",
    scheduledDate: "2026-09-06",
    status: "Completed",
    priority: "Medium",
    officerInCharge: "Maj. S. K. Nair",
  },
  {
    id: "INT-884",
    personnelId: "P-1026",
    personnelName: "HC. Amitav Banerjee",
    personnelRank: "Head Constable",
    type: "Sleep Hygiene Protocol",
    title: "Circadian Lighting & Nutrition Plan",
    description: "Unit medical officer prescribed magnesium supplementation and blue-light filtration post night patrol.",
    initiatedDate: "2026-09-07",
    scheduledDate: "2026-09-14",
    status: "Scheduled",
    priority: "Standard",
    officerInCharge: "Capt. M. Verma",
  },
];

export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: "REC-401",
    category: "Operational",
    title: "Implement 72-Hour Tactical Pause for 74 Bn Bravo Coy",
    reason: "Unit aggregate stress index reached 78.4 across 42 jawans on continuous night road opening patrol (ROP).",
    recommendedAction: "Relieve Bravo Coy with Delta Coy for 3 duty cycles; execute hydration and wellness debrief.",
    expectedRiskReductionPct: 34,
    confidenceScore: 94,
    status: "New",
    targetUnit: "74 Bn Bravo Company",
  },
  {
    id: "REC-402",
    category: "Clinical",
    title: "Dispatch Mobile Tele-Counseling Unit to Sukma Forward FOB",
    reason: "3 independent anti-masking high-confidence flags detected in platoon 2 within 48 hours.",
    recommendedAction: "Arrange encrypted satellite tele-consultation with MHA Tele-MANAS defense psychiatrists.",
    expectedRiskReductionPct: 28,
    confidenceScore: 91,
    status: "Approved",
    targetUnit: "Sukma Sector FOB 4",
  },
  {
    id: "REC-403",
    category: "Policy",
    title: "Restructure Siachen High-Altitude Acclimatization Cycles",
    reason: "Consecutive days beyond 90 days correlated with exponential sleep deficit spikes.",
    recommendedAction: "Cap continuous GL-1 post tenure to maximum 75 days with mandatory Leh transit rest.",
    expectedRiskReductionPct: 42,
    confidenceScore: 96,
    status: "New",
    targetUnit: "Northern Command Glaciers",
  },
  {
    id: "REC-404",
    category: "Tactical",
    title: "Synchronize Buddy-Pair Check-ins Before Weapon Arming",
    reason: "Mutual care check-in completion rates drop to 40% during rapid alert mobilizations.",
    recommendedAction: "Enforce automated digital buddy acknowledgment in kote (armory) checkout protocol.",
    expectedRiskReductionPct: 22,
    confidenceScore: 89,
    status: "Assigned",
    targetUnit: "All Battalion Kotes",
  },
];

export const MOCK_AUDIT_TRAIL: AuditLogEntry[] = [
  {
    id: "AUD-991",
    timestamp: "2026-09-11 11:42:15 IST",
    user: "Dr. Ananya Roy (SMO)",
    role: "WELFARE_OFFICER",
    action: "READ_CLINICAL_DOSSIER",
    resource: "Personnel/P-1024/MedicalHistory",
    ipAddress: "10.42.18.91 (Intranet)",
    status: "Success",
    sha256Hash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  },
  {
    id: "AUD-992",
    timestamp: "2026-09-11 10:15:30 IST",
    user: "Col. R. S. Rathore",
    role: "COMMANDER",
    action: "APPROVE_DARBAR_AUDIENCE",
    resource: "Darbar/DAR-101/ScheduleSlot",
    ipAddress: "10.42.18.12 (Intranet)",
    status: "Success",
    sha256Hash: "8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4",
  },
  {
    id: "AUD-993",
    timestamp: "2026-09-11 09:30:00 IST",
    user: "Ct. Vikramaditya Singh",
    role: "PERSONNEL",
    action: "SUBMIT_SELF_ASSESSMENT",
    resource: "Wellness/Survey/6-Step-Voluntary",
    ipAddress: "192.168.1.104 (Camp WiFi)",
    status: "Success",
    sha256Hash: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
  },
  {
    id: "AUD-994",
    timestamp: "2026-09-11 08:14:22 IST",
    user: "Security Gatekeeper (AI Engine)",
    role: "SYSTEM",
    action: "DETECT_ANTI_MASKING_ANOMALY",
    resource: "InferenceEngine/LightGBM-v4",
    ipAddress: "127.0.0.1 (Local IPC)",
    status: "Success",
    sha256Hash: "4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
  },
  {
    id: "AUD-995",
    timestamp: "2026-09-10 23:19:04 IST",
    user: "Unauthorized Access Probe",
    role: "GUEST",
    action: "ATTEMPT_EXPORT_UNENCRYPTED_PII",
    resource: "Database/Personnel/Restricted",
    ipAddress: "172.56.21.99 (External WAN)",
    status: "Blocked",
    sha256Hash: "ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d",
  },
];
